package com.mycompany.comsc_1451_project;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Christopher
 */
public class Add_Basic_Bike extends javax.swing.JFrame {
    static boolean   submitButton_BasicBike_clicked;

    /**
     * Creates new form ABB
     */
    public Add_Basic_Bike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sp_r_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        g_tr_s_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        paint_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        s_sf_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        submitButton1_adBasicBike_addMenu = new javax.swing.JButton();
        BackButton_addBasicBike_addMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Basic Bike Menu");

        jLabel2.setText("Speed rating");

        sp_r_input_box_BasicBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_r_input_box_BasicBike_addMenuActionPerformed(evt);
            }
        });

        submitButton1_adBasicBike_addMenu.setText("Submit");
        submitButton1_adBasicBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1_adBasicBike_addMenuActionPerformed(evt);
            }
        });

        BackButton_addBasicBike_addMenu.setText("Go Back");
        BackButton_addBasicBike_addMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton_addBasicBike_addMenuMouseClicked(evt);
            }
        });
        BackButton_addBasicBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_addBasicBike_addMenuActionPerformed(evt);
            }
        });

        jLabel3.setText("Gear Train");

        jLabel4.setText("Paint Scheme");

        jLabel5.setText("Special and Safety Features");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(g_tr_s_input_box_BasicBike_addMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_r_input_box_BasicBike_addMenu)
                    .addComponent(paint_input_box_BasicBike_addMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s_sf_input_box_BasicBike_addMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton_addBasicBike_addMenu)
                                .addGap(238, 238, 238)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(338, 338, 338)
                                .addComponent(submitButton1_adBasicBike_addMenu)))
                        .addGap(0, 228, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton_addBasicBike_addMenu)))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(sp_r_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g_tr_s_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paint_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s_sf_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(submitButton1_adBasicBike_addMenu)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


//return to previous screen
    private void BackButton_addBasicBike_addMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_addBasicBike_addMenuMouseClicked
        this.toBack();
        setVisible(false);
        new Add_Bike_Menu().toFront();
        new Add_Bike_Menu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_BackButton_addBasicBike_addMenuMouseClicked

    private void submitButton1_adBasicBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1_adBasicBike_addMenuActionPerformed
        
        InventoryControlGUI. sp_r_BasicBike_add = Integer.parseInt(sp_r_input_box_BasicBike_addMenu.getText());
        InventoryControlGUI. gtr_s_BasicBike_add = Integer.parseInt(g_tr_s_input_box_BasicBike_addMenu.getText());
        InventoryControlGUI.paint_BasicBike_add = paint_input_box_BasicBike_addMenu.getText().toString();
        InventoryControlGUI.s_sf_BasicBike_add = s_sf_input_box_BasicBike_addMenu.getText();
        InventoryControlGUI.addToBasicBikeInventory( InventoryControlGUI.myBasicBikeInventory,true,100);
        
    }//GEN-LAST:event_submitButton1_adBasicBike_addMenuActionPerformed

    private void sp_r_input_box_BasicBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_r_input_box_BasicBike_addMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_r_input_box_BasicBike_addMenuActionPerformed

    private void BackButton_addBasicBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_addBasicBike_addMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButton_addBasicBike_addMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Basic_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Basic_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Basic_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Basic_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Basic_Bike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_addBasicBike_addMenu;
    private javax.swing.JTextField g_tr_s_input_box_BasicBike_addMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField paint_input_box_BasicBike_addMenu;
    private javax.swing.JTextField s_sf_input_box_BasicBike_addMenu;
    private javax.swing.JTextField sp_r_input_box_BasicBike_addMenu;
    private javax.swing.JButton submitButton1_adBasicBike_addMenu;
    // End of variables declaration//GEN-END:variables
}
