/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class Add_E_Bike extends javax.swing.JFrame {
    static boolean   submitButton_EBike_clicked;


    /**
     * Creates new form Add_E_Bike
     */
    public Add_E_Bike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBack_Ebike_AddMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sp_r_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        g_tr_s_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paint_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s_sf_input_box_EBike_addMenu = new javax.swing.JTextField();
        SubmitButton_Ebike_AddMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sh_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fpt_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fs_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rm_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bty_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bsz_input_box_EBike_addMenu = new javax.swing.JTextField();
        mp_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bvt_input_box_EBike_addMenu1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goBack_Ebike_AddMenu.setText("Go Back");
        goBack_Ebike_AddMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBack_Ebike_AddMenuMouseClicked(evt);
            }
        });

        jLabel1.setText("Add Electric Bike Menu");

        jLabel2.setText("Speed rating");

        sp_r_input_box_EBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_r_input_box_EBike_addMenuActionPerformed(evt);
            }
        });

        jLabel3.setText("Gear Train");

        jLabel4.setText("Paint Scheme");

        jLabel5.setText("Special and Safety Features");

        SubmitButton_Ebike_AddMenu.setText("Submit");
        SubmitButton_Ebike_AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton_Ebike_AddMenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Bike Seat Height");

        jLabel7.setText("Flat Proof tires?");

        jLabel8.setText("Full Suspension?");

        jLabel9.setText("Range in miles");

        jLabel10.setText("Battery Type");

        jLabel11.setText("Battery Size");

        jLabel14.setText("Motor Power");

        jLabel15.setText("Battery Voltage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(g_tr_s_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                        .addComponent(s_sf_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sh_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fpt_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(goBack_Ebike_AddMenu)
                            .addGap(238, 238, 238)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paint_input_box_EBike_addMenu))
                    .addComponent(sp_r_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bvt_input_box_EBike_addMenu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(fs_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rm_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bty_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsz_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mp_input_box_EBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(SubmitButton_Ebike_AddMenu)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goBack_Ebike_AddMenu)))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sp_r_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g_tr_s_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paint_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s_sf_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sh_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fpt_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fs_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rm_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(bty_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bsz_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(mp_input_box_EBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bvt_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addComponent(SubmitButton_Ebike_AddMenu)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBack_Ebike_AddMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBack_Ebike_AddMenuMouseClicked
        this.toBack();
        setVisible(false);
        new Add_Bike_Menu().toFront();
        new Add_Bike_Menu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_goBack_Ebike_AddMenuMouseClicked

    private void sp_r_input_box_EBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_r_input_box_EBike_addMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_r_input_box_EBike_addMenuActionPerformed

    private void SubmitButton_Ebike_AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton_Ebike_AddMenuActionPerformed
        submitButton_EBike_clicked = true;
        InventoryControlGUI.sp_r_EBike_add = Integer.parseInt(sp_r_input_box_EBike_addMenu.getText());
        InventoryControlGUI.gtr_s_EBike_add = Integer.parseInt(g_tr_s_input_box_EBike_addMenu.getText());
        InventoryControlGUI.paint_EBike_add = paint_input_box_EBike_addMenu.getText().toString();
        InventoryControlGUI.s_sf_EBike_add = s_sf_input_box_EBike_addMenu.getText();
        InventoryControlGUI.sh_EBike_add = Integer.parseInt(sh_input_box_EBike_addMenu.getText());
        InventoryControlGUI.fpt_EBike_add = Boolean.parseBoolean(fpt_input_box_EBike_addMenu.getText());
        InventoryControlGUI.fs_EBike_add = Boolean.parseBoolean(fs_input_box_EBike_addMenu.getText());
        InventoryControlGUI.rm_Ebike_add = Integer.parseInt(rm_input_box_EBike_addMenu.getText());
        InventoryControlGUI.bty_EBike_add = bty_input_box_EBike_addMenu.getText().toString();
        InventoryControlGUI.bsz_EBike_add = Integer.parseInt(bsz_input_box_EBike_addMenu.getText());
        InventoryControlGUI.bvt_EBike_add = Integer.parseInt(bvt_input_box_EBike_addMenu1.getText());
        InventoryControlGUI.mp_EBike_add = Double.parseDouble(mp_input_box_EBike_addMenu.getText());
        InventoryControlGUI.addToEBikeInventory( InventoryControlGUI.myEBikeInventory,true,100);

    }//GEN-LAST:event_SubmitButton_Ebike_AddMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_E_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_E_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_E_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_E_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_E_Bike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitButton_Ebike_AddMenu;
    private javax.swing.JTextField bsz_input_box_EBike_addMenu;
    private javax.swing.JTextField bty_input_box_EBike_addMenu;
    private javax.swing.JTextField bvt_input_box_EBike_addMenu1;
    private javax.swing.JTextField fpt_input_box_EBike_addMenu;
    private javax.swing.JTextField fs_input_box_EBike_addMenu;
    private javax.swing.JTextField g_tr_s_input_box_EBike_addMenu;
    private javax.swing.JButton goBack_Ebike_AddMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mp_input_box_EBike_addMenu;
    private javax.swing.JTextField paint_input_box_EBike_addMenu;
    private javax.swing.JTextField rm_input_box_EBike_addMenu;
    private javax.swing.JTextField s_sf_input_box_EBike_addMenu;
    private javax.swing.JTextField sh_input_box_EBike_addMenu;
    private javax.swing.JTextField sp_r_input_box_EBike_addMenu;
    // End of variables declaration//GEN-END:variables
}
