/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

import static com.mycompany.comsc_1451_project.InventoryControlGUI.addToMountainBikeInventory;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.fpt_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.fs_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.gtr_s_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.myMountainBikeInventory;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.paint_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.s_sf_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.sh_MountainBike_add;
import static com.mycompany.comsc_1451_project.InventoryControlGUI.sp_r_MountainBike_add;

/**
 *
 * @author Christopher
 */
public class Add_Mountain_Bike extends javax.swing.JFrame {
        static boolean   submitButton_MountainBike_clicked;


    /**
     * Creates new form Add_Mountain_Bike
     */
    public Add_Mountain_Bike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sp_r_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        g_tr_s_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paint_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s_sf_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        SubmitButton_MountainBike_AddMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sh_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fpt_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fs_input_box_MountainBike_addMenu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Go Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Mountain Bike Menu");

        jLabel2.setText("Speed rating");

        jLabel3.setText("Gear Train");

        jLabel4.setText("Paint Scheme");

        jLabel5.setText("Special and Safety Features");

        SubmitButton_MountainBike_AddMenu.setText("Submit");
        SubmitButton_MountainBike_AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton_MountainBike_AddMenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Seat Height");

        jLabel7.setText("Flat Proof Tires");

        jLabel8.setText("Full Suspension");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(g_tr_s_input_box_MountainBike_addMenu, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sp_r_input_box_MountainBike_addMenu)
            .addComponent(paint_input_box_MountainBike_addMenu, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(s_sf_input_box_MountainBike_addMenu)
            .addComponent(sh_input_box_MountainBike_addMenu)
            .addComponent(fpt_input_box_MountainBike_addMenu)
            .addComponent(fs_input_box_MountainBike_addMenu)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 322, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(SubmitButton_MountainBike_AddMenu)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(sp_r_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g_tr_s_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paint_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s_sf_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sh_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fpt_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fs_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(SubmitButton_MountainBike_AddMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.toBack();
        setVisible(false);
        new Add_Bike_Menu().toFront();
        new Add_Bike_Menu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton2MouseClicked

    private void SubmitButton_MountainBike_AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton_MountainBike_AddMenuActionPerformed
        sp_r_MountainBike_add = Integer.parseInt(sp_r_input_box_MountainBike_addMenu.getText());
        gtr_s_MountainBike_add = Integer.parseInt(g_tr_s_input_box_MountainBike_addMenu.getText());
        paint_MountainBike_add = paint_input_box_MountainBike_addMenu.getText().toString();
        s_sf_MountainBike_add = s_sf_input_box_MountainBike_addMenu.getText();
        sh_MountainBike_add = Integer.parseInt(sh_input_box_MountainBike_addMenu.getText());
        fpt_MountainBike_add = Boolean.parseBoolean(fpt_input_box_MountainBike_addMenu.getText());
        fs_MountainBike_add = Boolean.parseBoolean(fs_input_box_MountainBike_addMenu.getText());
        InventoryControlGUI.addToMountainBikeInventory(myMountainBikeInventory, true, 100);
        
    }//GEN-LAST:event_SubmitButton_MountainBike_AddMenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //
        
        this.toBack();
        setVisible(false);
        new Add_Bike_Menu().toFront();
        new Add_Bike_Menu().setState(java.awt.Frame.NORMAL);
                                                     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Mountain_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Mountain_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Mountain_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Mountain_Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Mountain_Bike().setVisible(true);
            }
        });
    }


  
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitButton_MountainBike_AddMenu;
    private javax.swing.JTextField fpt_input_box_MountainBike_addMenu;
    private javax.swing.JTextField fs_input_box_MountainBike_addMenu;
    private javax.swing.JTextField g_tr_s_input_box_MountainBike_addMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField paint_input_box_MountainBike_addMenu;
    private javax.swing.JTextField s_sf_input_box_MountainBike_addMenu;
    private javax.swing.JTextField sh_input_box_MountainBike_addMenu;
    private javax.swing.JTextField sp_r_input_box_MountainBike_addMenu;
    // End of variables declaration//GEN-END:variables
}
