/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class Add_Bike_Menu extends javax.swing.JFrame {

    /**
     * Creates new form ABM
     */
    public Add_Bike_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoBackButtonAddBikesMenu = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        AddBasicBikeButton = new javax.swing.JButton();
        AddMountainBikeButton = new javax.swing.JButton();
        AddRoadBikeButton = new javax.swing.JButton();
        AddEBikeButton = new javax.swing.JButton();
        AddERoadBikeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoBackButtonAddBikesMenu.setText("Go Back");
        GoBackButtonAddBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonAddBikesMenuMouseClicked(evt);
            }
        });
        GoBackButtonAddBikesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonAddBikesMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Bikes Menu");

        AddBasicBikeButton.setText("Add Basic Bike");
        AddBasicBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBasicBikeButtonMouseClicked(evt);
            }
        });
        AddBasicBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBasicBikeButtonActionPerformed(evt);
            }
        });

        AddMountainBikeButton.setText("Add Mountain Bike");
        AddMountainBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMountainBikeButtonMouseClicked(evt);
            }
        });

        AddRoadBikeButton.setText("Add Road Bike");
        AddRoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRoadBikeButtonMouseClicked(evt);
            }
        });

        AddEBikeButton.setText("Add Electric Bike");
        AddEBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEBikeButtonMouseClicked(evt);
            }
        });

        AddERoadBikeButton.setText("Add Electric Road Bike");
        AddERoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddERoadBikeButtonMouseClicked(evt);
            }
        });
        AddERoadBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddERoadBikeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddMountainBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBasicBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddRoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddEBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddERoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GoBackButtonAddBikesMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(172, 172, 172)))
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(GoBackButtonAddBikesMenu))
                .addGap(50, 50, 50)
                .addComponent(AddBasicBikeButton)
                .addGap(18, 18, 18)
                .addComponent(AddMountainBikeButton)
                .addGap(18, 18, 18)
                .addComponent(AddRoadBikeButton)
                .addGap(18, 18, 18)
                .addComponent(AddEBikeButton)
                .addGap(18, 18, 18)
                .addComponent(AddERoadBikeButton)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonAddBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuMouseClicked
        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonAddBikesMenuMouseClicked

    private void GoBackButtonAddBikesMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void AddBasicBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBasicBikeButtonMouseClicked
         this.toBack();
    Add_Basic_Bike a =new Add_Basic_Bike();
    a.setVisible(true);
    a.toFront();
    }//GEN-LAST:event_AddBasicBikeButtonMouseClicked

    private void AddMountainBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMountainBikeButtonMouseClicked
    this.toBack();
    Add_Mountain_Bike a =new Add_Mountain_Bike();
    a.setVisible(true);
    a.toFront();
    }//GEN-LAST:event_AddMountainBikeButtonMouseClicked

    private void AddRoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRoadBikeButtonMouseClicked
        
    this.toFront();
    Add_Road_Bike a =new Add_Road_Bike();
    a.setVisible(true);
    a.toFront();
        
    }//GEN-LAST:event_AddRoadBikeButtonMouseClicked

    private void AddEBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEBikeButtonMouseClicked
    this.toBack();
    Add_E_Bike a = new Add_E_Bike();
    a.setVisible(true);
    a.toFront();
    }//GEN-LAST:event_AddEBikeButtonMouseClicked

    private void AddBasicBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBasicBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBasicBikeButtonActionPerformed

    private void AddERoadBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddERoadBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddERoadBikeButtonActionPerformed

    private void AddERoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddERoadBikeButtonMouseClicked
    this.toBack();
    Add_E_RoadBike a = new Add_E_RoadBike();
    a.setVisible(true);
    a.toFront();

    }//GEN-LAST:event_AddERoadBikeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Bike_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Bike_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Bike_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Bike_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Bike_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBasicBikeButton;
    private javax.swing.JButton AddEBikeButton;
    private javax.swing.JButton AddERoadBikeButton;
    private javax.swing.JButton AddMountainBikeButton;
    private javax.swing.JButton AddRoadBikeButton;
    private javax.swing.JToggleButton GoBackButtonAddBikesMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
