/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DeleteMountainBike extends javax.swing.JFrame {

    /**
     * Creates new form DeleteMountainBike
     */
    public DeleteMountainBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoBackButtonDeleteBikesMenu_MB = new javax.swing.JToggleButton();
        fbgjLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DELETEbike_finalConfirm_DeleteMBike = new javax.swing.JButton();
        targetDelete_input_box_DeleteMBike = new javax.swing.JTextField();
        DeleteBikeConfirm_DeleteMBike = new javax.swing.JTextField();
        SubmitTargetDeleteButton_DeleteMBike = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoBackButtonDeleteBikesMenu_MB.setText("Go Back");
        GoBackButtonDeleteBikesMenu_MB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDeleteBikesMenu_MBMouseClicked(evt);
            }
        });
        GoBackButtonDeleteBikesMenu_MB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDeleteBikesMenu_MBActionPerformed(evt);
            }
        });

        fbgjLabel1.setText("Delete Mountain Bike Menu");

        jLabel1.setText("Enter Bike number to delete");

        jLabel3.setText("Y/N:");

        jLabel2.setText("Are you absolutely sure that you want to delete this bike? :");

        DELETEbike_finalConfirm_DeleteMBike.setText("DELETE THIS BIKE");
        DELETEbike_finalConfirm_DeleteMBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEbike_finalConfirm_DeleteMBikeMouseClicked(evt);
            }
        });
        DELETEbike_finalConfirm_DeleteMBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEbike_finalConfirm_DeleteMBikeActionPerformed(evt);
            }
        });

        targetDelete_input_box_DeleteMBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetDelete_input_box_DeleteMBikeActionPerformed(evt);
            }
        });

        SubmitTargetDeleteButton_DeleteMBike.setText("Submit");
        SubmitTargetDeleteButton_DeleteMBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitTargetDeleteButton_DeleteMBikeMouseClicked(evt);
            }
        });
        SubmitTargetDeleteButton_DeleteMBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitTargetDeleteButton_DeleteMBikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBikeConfirm_DeleteMBike, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DELETEbike_finalConfirm_DeleteMBike))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GoBackButtonDeleteBikesMenu_MB)
                                .addGap(75, 75, 75)
                                .addComponent(fbgjLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetDelete_input_box_DeleteMBike, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitTargetDeleteButton_DeleteMBike)))
                        .addGap(157, 248, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBackButtonDeleteBikesMenu_MB)
                    .addComponent(fbgjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDelete_input_box_DeleteMBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitTargetDeleteButton_DeleteMBike))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DeleteBikeConfirm_DeleteMBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEbike_finalConfirm_DeleteMBike))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonDeleteBikesMenu_MBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_MBMouseClicked
        this.toBack();
        setVisible(false);
        new DeleteBikesMenu().toFront();
        new DeleteBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_MBMouseClicked

    private void GoBackButtonDeleteBikesMenu_MBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_MBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_MBActionPerformed

    private void DELETEbike_finalConfirm_DeleteMBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteMBikeMouseClicked
        InventoryControlGUI.removeFromMountainBikeInventory(InventoryControlGUI.myMountainBikeInventory,true,100);

        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteMBikeMouseClicked

    private void targetDelete_input_box_DeleteMBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetDelete_input_box_DeleteMBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetDelete_input_box_DeleteMBikeActionPerformed

    private void SubmitTargetDeleteButton_DeleteMBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteMBikeMouseClicked

        InventoryControlGUI.targetDelete_MBike = Integer.parseInt(DeleteMountainBike.targetDelete_input_box_DeleteMBike.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteMBikeMouseClicked

    private void SubmitTargetDeleteButton_DeleteMBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteMBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteMBikeActionPerformed

    private void DELETEbike_finalConfirm_DeleteMBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteMBikeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteMBikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteMountainBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETEbike_finalConfirm_DeleteMBike;
    public static javax.swing.JTextField DeleteBikeConfirm_DeleteMBike;
    private javax.swing.JToggleButton GoBackButtonDeleteBikesMenu_MB;
    private javax.swing.JButton SubmitTargetDeleteButton_DeleteMBike;
    private javax.swing.JLabel fbgjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField targetDelete_input_box_DeleteMBike;
    // End of variables declaration//GEN-END:variables
}
