/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DeleteERoadBike extends javax.swing.JFrame {

    /**
     * Creates new form DeleteERoadBike
     */
    public DeleteERoadBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteBikeConfirm_DeleteERBike = new javax.swing.JTextField();
        SubmitTargetDeleteButton_DeleteERBike = new javax.swing.JButton();
        GoBackButtonDeleteBikesMenu_ERB = new javax.swing.JToggleButton();
        fbgjLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DELETEbike_finalConfirm_DeleteERBike = new javax.swing.JButton();
        targetDelete_input_box_DeleteERBike = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitTargetDeleteButton_DeleteERBike.setText("Submit");
        SubmitTargetDeleteButton_DeleteERBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitTargetDeleteButton_DeleteERBikeMouseClicked(evt);
            }
        });
        SubmitTargetDeleteButton_DeleteERBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitTargetDeleteButton_DeleteERBikeActionPerformed(evt);
            }
        });

        GoBackButtonDeleteBikesMenu_ERB.setText("Go Back");
        GoBackButtonDeleteBikesMenu_ERB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDeleteBikesMenu_ERBMouseClicked(evt);
            }
        });
        GoBackButtonDeleteBikesMenu_ERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDeleteBikesMenu_ERBActionPerformed(evt);
            }
        });

        fbgjLabel1.setText("Delete Electric Road Bike Menu");

        jLabel1.setText("Enter Bike number to delete");

        jLabel3.setText("Y/N:");

        jLabel2.setText("Are you absolutely sure that you want to delete this bike? :");

        DELETEbike_finalConfirm_DeleteERBike.setText("DELETE THIS BIKE");
        DELETEbike_finalConfirm_DeleteERBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEbike_finalConfirm_DeleteERBikeMouseClicked(evt);
            }
        });
        DELETEbike_finalConfirm_DeleteERBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEbike_finalConfirm_DeleteERBikeActionPerformed(evt);
            }
        });

        targetDelete_input_box_DeleteERBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetDelete_input_box_DeleteERBikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBikeConfirm_DeleteERBike, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DELETEbike_finalConfirm_DeleteERBike))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GoBackButtonDeleteBikesMenu_ERB)
                                .addGap(51, 51, 51)
                                .addComponent(fbgjLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetDelete_input_box_DeleteERBike, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitTargetDeleteButton_DeleteERBike)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBackButtonDeleteBikesMenu_ERB)
                    .addComponent(fbgjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDelete_input_box_DeleteERBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitTargetDeleteButton_DeleteERBike))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DeleteBikeConfirm_DeleteERBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEbike_finalConfirm_DeleteERBike))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitTargetDeleteButton_DeleteERBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteERBikeMouseClicked

        InventoryControlGUI.targetDelete_ERBike = Integer.parseInt(DeleteERoadBike.targetDelete_input_box_DeleteERBike.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteERBikeMouseClicked

    private void SubmitTargetDeleteButton_DeleteERBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteERBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteERBikeActionPerformed

    private void GoBackButtonDeleteBikesMenu_ERBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_ERBMouseClicked
        this.toBack();
        setVisible(false);
        new DeleteBikesMenu().toFront();
        new DeleteBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_ERBMouseClicked

    private void GoBackButtonDeleteBikesMenu_ERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_ERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_ERBActionPerformed

    private void DELETEbike_finalConfirm_DeleteERBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteERBikeMouseClicked
        InventoryControlGUI.removeFromERoadBikeInventory(InventoryControlGUI.myERoadBikeInventory,true,100);

        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteERBikeMouseClicked

    private void DELETEbike_finalConfirm_DeleteERBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteERBikeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteERBikeActionPerformed

    private void targetDelete_input_box_DeleteERBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetDelete_input_box_DeleteERBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetDelete_input_box_DeleteERBikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteERoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteERoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteERoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteERoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteERoadBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETEbike_finalConfirm_DeleteERBike;
    public static javax.swing.JTextField DeleteBikeConfirm_DeleteERBike;
    private javax.swing.JToggleButton GoBackButtonDeleteBikesMenu_ERB;
    private javax.swing.JButton SubmitTargetDeleteButton_DeleteERBike;
    private javax.swing.JLabel fbgjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField targetDelete_input_box_DeleteERBike;
    // End of variables declaration//GEN-END:variables
}
