/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DeleteEBike extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEBike
     */
    public DeleteEBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeleteBikeConfirm_DeleteEBike = new javax.swing.JTextField();
        SubmitTargetDeleteButton_DeleteEBike = new javax.swing.JButton();
        GoBackButtonDeleteBikesMenu_EB = new javax.swing.JToggleButton();
        fbgjLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DELETEbike_finalConfirm_DeleteEBike = new javax.swing.JButton();
        targetDelete_input_box_DeleteEBike = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitTargetDeleteButton_DeleteEBike.setText("Submit");
        SubmitTargetDeleteButton_DeleteEBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitTargetDeleteButton_DeleteEBikeMouseClicked(evt);
            }
        });
        SubmitTargetDeleteButton_DeleteEBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitTargetDeleteButton_DeleteEBikeActionPerformed(evt);
            }
        });

        GoBackButtonDeleteBikesMenu_EB.setText("Go Back");
        GoBackButtonDeleteBikesMenu_EB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDeleteBikesMenu_EBMouseClicked(evt);
            }
        });
        GoBackButtonDeleteBikesMenu_EB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDeleteBikesMenu_EBActionPerformed(evt);
            }
        });

        fbgjLabel1.setText("Delete Electric Bike Menu");

        jLabel1.setText("Enter Bike number to delete");

        jLabel3.setText("Y/N:");

        jLabel2.setText("Are you absolutely sure that you want to delete this bike? :");

        DELETEbike_finalConfirm_DeleteEBike.setText("DELETE THIS BIKE");
        DELETEbike_finalConfirm_DeleteEBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEbike_finalConfirm_DeleteEBikeMouseClicked(evt);
            }
        });
        DELETEbike_finalConfirm_DeleteEBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEbike_finalConfirm_DeleteEBikeActionPerformed(evt);
            }
        });

        targetDelete_input_box_DeleteEBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetDelete_input_box_DeleteEBikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBikeConfirm_DeleteEBike, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DELETEbike_finalConfirm_DeleteEBike))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GoBackButtonDeleteBikesMenu_EB)
                                .addGap(41, 41, 41)
                                .addComponent(fbgjLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetDelete_input_box_DeleteEBike, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitTargetDeleteButton_DeleteEBike)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBackButtonDeleteBikesMenu_EB)
                    .addComponent(fbgjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDelete_input_box_DeleteEBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitTargetDeleteButton_DeleteEBike))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DeleteBikeConfirm_DeleteEBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEbike_finalConfirm_DeleteEBike))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitTargetDeleteButton_DeleteEBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteEBikeMouseClicked

        InventoryControlGUI.targetDelete_EBike = Integer.parseInt(DeleteEBike.targetDelete_input_box_DeleteEBike.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteEBikeMouseClicked

    private void SubmitTargetDeleteButton_DeleteEBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteEBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteEBikeActionPerformed

    private void GoBackButtonDeleteBikesMenu_EBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_EBMouseClicked
        this.toBack();
        setVisible(false);
        new DeleteBikesMenu().toFront();
        new DeleteBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_EBMouseClicked

    private void GoBackButtonDeleteBikesMenu_EBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_EBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_EBActionPerformed

    private void DELETEbike_finalConfirm_DeleteEBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteEBikeMouseClicked
        InventoryControlGUI.removeFromEBikeInventory(InventoryControlGUI.myEBikeInventory,true,100);

        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteEBikeMouseClicked

    private void DELETEbike_finalConfirm_DeleteEBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteEBikeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteEBikeActionPerformed

    private void targetDelete_input_box_DeleteEBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetDelete_input_box_DeleteEBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetDelete_input_box_DeleteEBikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETEbike_finalConfirm_DeleteEBike;
    public static javax.swing.JTextField DeleteBikeConfirm_DeleteEBike;
    private javax.swing.JToggleButton GoBackButtonDeleteBikesMenu_EB;
    private javax.swing.JButton SubmitTargetDeleteButton_DeleteEBike;
    private javax.swing.JLabel fbgjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField targetDelete_input_box_DeleteEBike;
    // End of variables declaration//GEN-END:variables
}
