/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DeleteBikesMenu extends javax.swing.JFrame {

    /**
     * Creates new form DeleteBikesMenu
     */
    public DeleteBikesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoBackButtonDeleteBikesMenu = new javax.swing.JToggleButton();
        DeleteBasicBikeButton = new javax.swing.JButton();
        DeleteMountainBikeButton = new javax.swing.JButton();
        DeleteRoadBikeButton = new javax.swing.JButton();
        DeleteElectricBikeButton = new javax.swing.JButton();
        DeleteElectricRoadBikeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoBackButtonDeleteBikesMenu.setText("Go Back");
        GoBackButtonDeleteBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDeleteBikesMenuMouseClicked(evt);
            }
        });
        GoBackButtonDeleteBikesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDeleteBikesMenuActionPerformed(evt);
            }
        });

        DeleteBasicBikeButton.setText("Delete Basic Bike");
        DeleteBasicBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBasicBikeButtonActionPerformed(evt);
            }
        });

        DeleteMountainBikeButton.setText("Delete Mountain Bike");
        DeleteMountainBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMountainBikeButtonMouseClicked(evt);
            }
        });
        DeleteMountainBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMountainBikeButtonActionPerformed(evt);
            }
        });

        DeleteRoadBikeButton.setText("Delete Road Bike");
        DeleteRoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteRoadBikeButtonMouseClicked(evt);
            }
        });
        DeleteRoadBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoadBikeButtonActionPerformed(evt);
            }
        });

        DeleteElectricBikeButton.setText("Delete Electric Bike");
        DeleteElectricBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteElectricBikeButtonMouseClicked(evt);
            }
        });
        DeleteElectricBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteElectricBikeButtonActionPerformed(evt);
            }
        });

        DeleteElectricRoadBikeButton.setText("Delete Electric Road Bike");
        DeleteElectricRoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteElectricRoadBikeButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Delete Bikes Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GoBackButtonDeleteBikesMenu)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteBasicBikeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteMountainBikeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteElectricBikeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteElectricRoadBikeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteRoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBackButtonDeleteBikesMenu)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addComponent(DeleteBasicBikeButton)
                .addGap(30, 30, 30)
                .addComponent(DeleteMountainBikeButton)
                .addGap(33, 33, 33)
                .addComponent(DeleteRoadBikeButton)
                .addGap(35, 35, 35)
                .addComponent(DeleteElectricBikeButton)
                .addGap(30, 30, 30)
                .addComponent(DeleteElectricRoadBikeButton)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonDeleteBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenuMouseClicked
        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenuMouseClicked

    private void GoBackButtonDeleteBikesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenuActionPerformed

    private void DeleteElectricBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteElectricBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteElectricBikeButtonActionPerformed

    private void DeleteBasicBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBasicBikeButtonActionPerformed

    this.toBack();
    DeleteBasicBike myDeleteBasicBike = new DeleteBasicBike();
    myDeleteBasicBike.setVisible(true);
    myDeleteBasicBike.toFront();


        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBasicBikeButtonActionPerformed

    private void DeleteMountainBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMountainBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMountainBikeButtonActionPerformed

    private void DeleteMountainBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMountainBikeButtonMouseClicked

this.toBack();
    DeleteMountainBike myDeleteMountainBike = new DeleteMountainBike();
    myDeleteMountainBike.setVisible(true);
    myDeleteMountainBike.toFront();



        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMountainBikeButtonMouseClicked

    private void DeleteRoadBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoadBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRoadBikeButtonActionPerformed

    private void DeleteRoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteRoadBikeButtonMouseClicked
    this.toBack();
    DeleteRoadBike myDeleteRoadBike = new DeleteRoadBike();
    myDeleteRoadBike.setVisible(true);
    myDeleteRoadBike.toFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRoadBikeButtonMouseClicked

    private void DeleteElectricBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteElectricBikeButtonMouseClicked

    this.toBack();
    DeleteEBike myDeleteEBike = new DeleteEBike();
    myDeleteEBike.setVisible(true);
    myDeleteEBike.toFront();


        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteElectricBikeButtonMouseClicked

    private void DeleteElectricRoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteElectricRoadBikeButtonMouseClicked

    this.toBack();
    DeleteERoadBike myDeleteERBike = new DeleteERoadBike();
    myDeleteERBike.setVisible(true);
    myDeleteERBike.toFront();


        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteElectricRoadBikeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteBikesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DeleteBasicBikeButton;
    public static javax.swing.JButton DeleteElectricBikeButton;
    public static javax.swing.JButton DeleteElectricRoadBikeButton;
    public static javax.swing.JButton DeleteMountainBikeButton;
    public static javax.swing.JButton DeleteRoadBikeButton;
    private javax.swing.JToggleButton GoBackButtonDeleteBikesMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
