/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DeleteRoadBike extends javax.swing.JFrame {

    /**
     * Creates new form DeleteRoadBike
     */
    public DeleteRoadBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoBackButtonDeleteBikesMenu_RB = new javax.swing.JToggleButton();
        fbgjLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        targetDelete_input_box_DeleteRBike = new javax.swing.JTextField();
        SubmitTargetDeleteButton_DeleteRBike = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeleteBikeConfirm_DeleteRBike = new javax.swing.JTextField();
        DELETEbike_finalConfirm_DeleteRBike = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoBackButtonDeleteBikesMenu_RB.setText("Go Back");
        GoBackButtonDeleteBikesMenu_RB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDeleteBikesMenu_RBMouseClicked(evt);
            }
        });
        GoBackButtonDeleteBikesMenu_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDeleteBikesMenu_RBActionPerformed(evt);
            }
        });

        fbgjLabel1.setText("Delete Road Bike Menu");

        jLabel1.setText("Enter Bike number to delete");

        targetDelete_input_box_DeleteRBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetDelete_input_box_DeleteRBikeActionPerformed(evt);
            }
        });

        SubmitTargetDeleteButton_DeleteRBike.setText("Submit");
        SubmitTargetDeleteButton_DeleteRBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitTargetDeleteButton_DeleteRBikeMouseClicked(evt);
            }
        });
        SubmitTargetDeleteButton_DeleteRBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitTargetDeleteButton_DeleteRBikeActionPerformed(evt);
            }
        });

        jLabel2.setText("Are you absolutely sure that you want to delete this bike? :");

        jLabel3.setText("Y/N:");

        DELETEbike_finalConfirm_DeleteRBike.setText("DELETE THIS BIKE");
        DELETEbike_finalConfirm_DeleteRBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEbike_finalConfirm_DeleteRBikeMouseClicked(evt);
            }
        });
        DELETEbike_finalConfirm_DeleteRBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEbike_finalConfirm_DeleteRBikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(targetDelete_input_box_DeleteRBike, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubmitTargetDeleteButton_DeleteRBike)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GoBackButtonDeleteBikesMenu_RB)
                                .addGap(98, 98, 98)
                                .addComponent(fbgjLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBikeConfirm_DeleteRBike, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DELETEbike_finalConfirm_DeleteRBike))
                            .addComponent(jLabel2))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoBackButtonDeleteBikesMenu_RB)
                    .addComponent(fbgjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetDelete_input_box_DeleteRBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitTargetDeleteButton_DeleteRBike))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DeleteBikeConfirm_DeleteRBike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEbike_finalConfirm_DeleteRBike))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonDeleteBikesMenu_RBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_RBMouseClicked
        this.toBack();
        setVisible(false);
        new DeleteBikesMenu().toFront();
        new DeleteBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_RBMouseClicked

    private void GoBackButtonDeleteBikesMenu_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDeleteBikesMenu_RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDeleteBikesMenu_RBActionPerformed

    private void targetDelete_input_box_DeleteRBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetDelete_input_box_DeleteRBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetDelete_input_box_DeleteRBikeActionPerformed

    private void SubmitTargetDeleteButton_DeleteRBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteRBikeMouseClicked

        InventoryControlGUI.targetDelete_RBike = Integer.parseInt(DeleteRoadBike.targetDelete_input_box_DeleteRBike.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteRBikeMouseClicked

    private void SubmitTargetDeleteButton_DeleteRBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitTargetDeleteButton_DeleteRBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitTargetDeleteButton_DeleteRBikeActionPerformed

    private void DELETEbike_finalConfirm_DeleteRBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteRBikeMouseClicked
        InventoryControlGUI.removeFromRoadBikeInventory(InventoryControlGUI.myRoadBikeInventory,true,100);

        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteRBikeMouseClicked

    private void DELETEbike_finalConfirm_DeleteRBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEbike_finalConfirm_DeleteRBikeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DELETEbike_finalConfirm_DeleteRBikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteRoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteRoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteRoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRoadBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRoadBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETEbike_finalConfirm_DeleteRBike;
    public static javax.swing.JTextField DeleteBikeConfirm_DeleteRBike;
    private javax.swing.JToggleButton GoBackButtonDeleteBikesMenu_RB;
    private javax.swing.JButton SubmitTargetDeleteButton_DeleteRBike;
    private javax.swing.JLabel fbgjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField targetDelete_input_box_DeleteRBike;
    // End of variables declaration//GEN-END:variables
}
