/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Christopher
 */

package com.mycompany.comsc_1451_project;

public class DisplayBikesMenu extends javax.swing.JFrame {

    /**
     * Creates new form DisplayBikesMenu
     */
    public DisplayBikesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButtonDisplayBikesMenu = new javax.swing.JToggleButton();
        DisplayBasicBikeInventory = new javax.swing.JButton();
        DisplayMountainBikeInventory1 = new javax.swing.JButton();
        DisplayEBikeInventory = new javax.swing.JButton();
        DisplayRoadBikeInventory = new javax.swing.JButton();
        DisplayERoadBikeInventory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Display Bikes Menu");

        BackButtonDisplayBikesMenu.setText("Go Back");
        BackButtonDisplayBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonDisplayBikesMenuMouseClicked(evt);
            }
        });

        DisplayBasicBikeInventory.setText("Display Basic Bike");
        DisplayBasicBikeInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayBasicBikeInventoryMouseClicked(evt);
            }
        });
        DisplayBasicBikeInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBasicBikeInventoryActionPerformed(evt);
            }
        });

        DisplayMountainBikeInventory1.setText("Display Mountain Bike");
        DisplayMountainBikeInventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayMountainBikeInventory1MouseClicked(evt);
            }
        });
        DisplayMountainBikeInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayMountainBikeInventory1ActionPerformed(evt);
            }
        });

        DisplayEBikeInventory.setText("Display Electric Bike");
        DisplayEBikeInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayEBikeInventoryMouseClicked(evt);
            }
        });

        DisplayRoadBikeInventory.setText("Display Road Bike");
        DisplayRoadBikeInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayRoadBikeInventoryMouseClicked(evt);
            }
        });
        DisplayRoadBikeInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRoadBikeInventoryActionPerformed(evt);
            }
        });

        DisplayERoadBikeInventory.setText("Display Electric Road Bike");
        DisplayERoadBikeInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayERoadBikeInventoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButtonDisplayBikesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DisplayEBikeInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayRoadBikeInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayMountainBikeInventory1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayBasicBikeInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayERoadBikeInventory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addComponent(BackButtonDisplayBikesMenu))
                .addGap(34, 34, 34)
                .addComponent(DisplayBasicBikeInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayMountainBikeInventory1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayRoadBikeInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayEBikeInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayERoadBikeInventory)
                .addGap(0, 333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void BackButtonDisplayBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonDisplayBikesMenuMouseClicked

        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);

    }//GEN-LAST:event_BackButtonDisplayBikesMenuMouseClicked

    private void DisplayBasicBikeInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBasicBikeInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayBasicBikeInventoryActionPerformed

    private void DisplayBasicBikeInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayBasicBikeInventoryMouseClicked

        this.toBack();
        DisplayBasicBike myDisplayBasicBikebutton = new DisplayBasicBike();
        myDisplayBasicBikebutton.setVisible(true);
        myDisplayBasicBikebutton.toFront();
        
        InventoryControlGUI.displayBasicBikeInventory(InventoryControlGUI.myBasicBikeInventory, true);

        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayBasicBikeInventoryMouseClicked

    private void DisplayMountainBikeInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayMountainBikeInventory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayMountainBikeInventory1ActionPerformed

    private void DisplayMountainBikeInventory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayMountainBikeInventory1MouseClicked
        this.toBack();
        DisplayMountainBike myDisplayMountainBikebutton = new DisplayMountainBike();
        myDisplayMountainBikebutton.setVisible(true);
        myDisplayMountainBikebutton.toFront();
        
        InventoryControlGUI.displayMountainBikeInventory(InventoryControlGUI.myMountainBikeInventory, true);



        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayMountainBikeInventory1MouseClicked

    private void DisplayRoadBikeInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRoadBikeInventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayRoadBikeInventoryActionPerformed

    private void DisplayRoadBikeInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayRoadBikeInventoryMouseClicked

        this.toBack();
        DisplayRoadBike myDisplayRoadBikebutton = new DisplayRoadBike();
        myDisplayRoadBikebutton.setVisible(true);
        myDisplayRoadBikebutton.toFront();
        
        InventoryControlGUI.displayRoadBikeInventory(InventoryControlGUI.myRoadBikeInventory, true);


        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayRoadBikeInventoryMouseClicked

    private void DisplayEBikeInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayEBikeInventoryMouseClicked

        this.toBack();
        DisplayEBike myDisplayEBikebutton = new DisplayEBike();
        myDisplayEBikebutton.setVisible(true);
        myDisplayEBikebutton.toFront();
        
        InventoryControlGUI.displayEBikeInventory(InventoryControlGUI.myEBikeInventory, true);



    }//GEN-LAST:event_DisplayEBikeInventoryMouseClicked

    private void DisplayERoadBikeInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayERoadBikeInventoryMouseClicked


        this.toBack();
        DisplayERoadBike myDisplayERoadBikebutton = new DisplayERoadBike();
        myDisplayERoadBikebutton.setVisible(true);
        myDisplayERoadBikebutton.toFront();
        
        InventoryControlGUI.displayERoadBikeInventory(InventoryControlGUI.myERoadBikeInventory, true);


    }//GEN-LAST:event_DisplayERoadBikeInventoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBikesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackButtonDisplayBikesMenu;
    private javax.swing.JButton DisplayBasicBikeInventory;
    private javax.swing.JButton DisplayEBikeInventory;
    private javax.swing.JButton DisplayERoadBikeInventory;
    private javax.swing.JButton DisplayMountainBikeInventory1;
    private javax.swing.JButton DisplayRoadBikeInventory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
