/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class DisplayMountainBike extends javax.swing.JFrame {

    /**
     * Creates new form DisplayMountainBike
     */
    public DisplayMountainBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayMBTextArea = new javax.swing.JTextArea();
        GoBackButtonDisplayMountainBike = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayMBTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        DisplayMBTextArea.setColumns(20);
        DisplayMBTextArea.setRows(5);
        jScrollPane1.setViewportView(DisplayMBTextArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoBackButtonDisplayMountainBike.setText("Go Back");
        GoBackButtonDisplayMountainBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonDisplayMountainBikeMouseClicked(evt);
            }
        });
        GoBackButtonDisplayMountainBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonDisplayMountainBikeActionPerformed(evt);
            }
        });

        DisplayMBTextArea1.setColumns(20);
        DisplayMBTextArea1.setRows(5);
        jScrollPane2.setViewportView(DisplayMBTextArea1);

        jLabel1.setText("Display Mountain Bike");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GoBackButtonDisplayMountainBike)
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addGap(0, 211, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoBackButtonDisplayMountainBike)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonDisplayMountainBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonDisplayMountainBikeMouseClicked
        this.toBack();
        setVisible(false);
        new DisplayBikesMenu().toFront();
        new DisplayBikesMenu().setState(java.awt.Frame.NORMAL);

    }//GEN-LAST:event_GoBackButtonDisplayMountainBikeMouseClicked

    private void GoBackButtonDisplayMountainBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonDisplayMountainBikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonDisplayMountainBikeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayMountainBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DisplayMBTextArea;
    public static javax.swing.JTextArea DisplayMBTextArea1;
    private javax.swing.JButton GoBackButtonDisplayMountainBike;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
