/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class EditEBike extends javax.swing.JFrame {

    /**
     * Creates new form EditBasicBike
     */
    public EditEBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        bsz_input_box_EBike_addMenu = new javax.swing.JTextField();
        mp_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bvt_input_box_EBike_addMenu1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rm_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bty_input_box_EBike_addMenu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GoBackButtonAddBikesMenu = new javax.swing.JToggleButton();
        bikeNumber_inputBox = new javax.swing.JTextField();
        s_sf_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        submitButton1_adBasicBike_addMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sp_r_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        g_tr_s_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        paint_input_box_BasicBike_addMenu = new javax.swing.JTextField();
        fpt_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fs_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sh_input_box_MountainBike_addMenu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bsz_input_box_EBike_addMenu1 = new javax.swing.JTextField();
        mp_input_box_EBike_addMenu1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bvt_input_box_EBike_addMenu2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rm_input_box_EBike_addMenu1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        bty_input_box_EBike_addMenu1 = new javax.swing.JTextField();

        jLabel11.setText("Battery Size");

        jLabel14.setText("Motor Power");

        jLabel15.setText("Battery Voltage");

        jLabel10.setText("Range in miles");

        jLabel12.setText("Battery Type");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit E Bike Menu-do not leave properties blank-");

        jLabel2.setText("Enter bike number to edit its properties:");

        GoBackButtonAddBikesMenu.setText("Go Back");
        GoBackButtonAddBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonAddBikesMenuMouseClicked(evt);
            }
        });
        GoBackButtonAddBikesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonAddBikesMenuActionPerformed(evt);
            }
        });

        submitButton1_adBasicBike_addMenu.setText("Submit");
        submitButton1_adBasicBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1_adBasicBike_addMenuActionPerformed(evt);
            }
        });

        jLabel3.setText("Gear Train");

        jLabel4.setText("Paint Scheme");

        jLabel5.setText("Special and Safety Features");

        jLabel7.setText("Speed rating");

        sp_r_input_box_BasicBike_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_r_input_box_BasicBike_addMenuActionPerformed(evt);
            }
        });

        jLabel8.setText("Full Suspension");

        jLabel6.setText("Seat Height");

        jLabel9.setText("Flat Proof Tires");

        jLabel13.setText("Battery Size");

        jLabel16.setText("Motor Power");

        jLabel17.setText("Battery Voltage");

        jLabel18.setText("Range in miles");

        jLabel19.setText("Battery Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(paint_input_box_BasicBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(s_sf_input_box_BasicBike_addMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sp_r_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g_tr_s_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sh_input_box_MountainBike_addMenu)
                            .addComponent(fpt_input_box_MountainBike_addMenu)
                            .addComponent(fs_input_box_MountainBike_addMenu)
                            .addComponent(rm_input_box_EBike_addMenu1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel18))
                                .addGap(0, 603, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bty_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(submitButton1_adBasicBike_addMenu)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(bsz_input_box_EBike_addMenu1)
                            .addComponent(mp_input_box_EBike_addMenu1)
                            .addComponent(bvt_input_box_EBike_addMenu2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(GoBackButtonAddBikesMenu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bikeNumber_inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(GoBackButtonAddBikesMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bikeNumber_inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sp_r_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g_tr_s_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paint_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sh_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fpt_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fs_input_box_MountainBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s_sf_input_box_BasicBike_addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rm_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(submitButton1_adBasicBike_addMenu)
                        .addContainerGap(200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bty_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsz_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(mp_input_box_EBike_addMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bvt_input_box_EBike_addMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonAddBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuMouseClicked
        this.toBack();
        setVisible(false);
        new EditBikesMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonAddBikesMenuMouseClicked

    private void GoBackButtonAddBikesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonAddBikesMenuActionPerformed

    private void submitButton1_adBasicBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1_adBasicBike_addMenuActionPerformed
        int BikeNumber = Integer.parseInt(bikeNumber_inputBox.getText());
        InventoryControlGUI. sp_r_BasicBike_add_EditMenu = Integer.parseInt(sp_r_input_box_BasicBike_addMenu.getText());
        InventoryControlGUI. gtr_s_BasicBike_add_EditMenu = Integer.parseInt(g_tr_s_input_box_BasicBike_addMenu.getText());
        InventoryControlGUI.paint_BasicBike_add_EditMenu = paint_input_box_BasicBike_addMenu.getText().toString();
        InventoryControlGUI.s_sf_BasicBike_add_EditMenu = s_sf_input_box_BasicBike_addMenu.getText();
           InventoryControlGUI.rm_Ebike_add_EditMenu = Integer.parseInt(rm_input_box_EBike_addMenu1.getText());
          InventoryControlGUI.bty_EBike_add_EditMenu = bty_input_box_EBike_addMenu1.getText();
          InventoryControlGUI.bsz_EBike_add_EditMenu = Integer.parseInt(bsz_input_box_EBike_addMenu1.getText());
          InventoryControlGUI.bvt_EBike_add_EditMenu = Integer.parseInt(bvt_input_box_EBike_addMenu2.getText());
          InventoryControlGUI.mp_EBike_add_EditMenu = Double.parseDouble(mp_input_box_EBike_addMenu1.getText());
        InventoryControlGUI.EditEBikeInventory( InventoryControlGUI.myEBikeInventory,100,BikeNumber);

    }//GEN-LAST:event_submitButton1_adBasicBike_addMenuActionPerformed

    private void sp_r_input_box_BasicBike_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_r_input_box_BasicBike_addMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp_r_input_box_BasicBike_addMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GoBackButtonAddBikesMenu;
    public static javax.swing.JTextField bikeNumber_inputBox;
    private javax.swing.JTextField bsz_input_box_EBike_addMenu;
    private javax.swing.JTextField bsz_input_box_EBike_addMenu1;
    private javax.swing.JTextField bty_input_box_EBike_addMenu;
    private javax.swing.JTextField bty_input_box_EBike_addMenu1;
    private javax.swing.JTextField bvt_input_box_EBike_addMenu1;
    private javax.swing.JTextField bvt_input_box_EBike_addMenu2;
    private javax.swing.JTextField fpt_input_box_MountainBike_addMenu;
    private javax.swing.JTextField fs_input_box_MountainBike_addMenu;
    private javax.swing.JTextField g_tr_s_input_box_BasicBike_addMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mp_input_box_EBike_addMenu;
    private javax.swing.JTextField mp_input_box_EBike_addMenu1;
    private javax.swing.JTextField paint_input_box_BasicBike_addMenu;
    private javax.swing.JTextField rm_input_box_EBike_addMenu;
    private javax.swing.JTextField rm_input_box_EBike_addMenu1;
    private javax.swing.JTextField s_sf_input_box_BasicBike_addMenu;
    private javax.swing.JTextField sh_input_box_MountainBike_addMenu;
    private javax.swing.JTextField sp_r_input_box_BasicBike_addMenu;
    private javax.swing.JButton submitButton1_adBasicBike_addMenu;
    // End of variables declaration//GEN-END:variables
}
