/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class EditBikesMenu extends javax.swing.JFrame {

    /**
     * Creates new form EditBikesMenu
     */
    public EditBikesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditMountainBikeButton = new javax.swing.JButton();
        EditRoadBikeButton = new javax.swing.JButton();
        EditEBikeButton = new javax.swing.JButton();
        EditERoadBikeButton = new javax.swing.JButton();
        GoBackButtonAddBikesMenu = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        EditBasicBikeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EditMountainBikeButton.setText("Edit  Mountain Bike");
        EditMountainBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMountainBikeButtonMouseClicked(evt);
            }
        });

        EditRoadBikeButton.setText("Edit  Road Bike");
        EditRoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditRoadBikeButtonMouseClicked(evt);
            }
        });

        EditEBikeButton.setText("Edit Electric Bike");
        EditEBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditEBikeButtonMouseClicked(evt);
            }
        });

        EditERoadBikeButton.setText("Edit Electric Road Bike");
        EditERoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditERoadBikeButtonMouseClicked(evt);
            }
        });
        EditERoadBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditERoadBikeButtonActionPerformed(evt);
            }
        });

        GoBackButtonAddBikesMenu.setText("Go Back");
        GoBackButtonAddBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonAddBikesMenuMouseClicked(evt);
            }
        });
        GoBackButtonAddBikesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonAddBikesMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Edit Bikes Menu");

        EditBasicBikeButton.setText("Edit Basic Bike");
        EditBasicBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBasicBikeButtonMouseClicked(evt);
            }
        });
        EditBasicBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBasicBikeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditMountainBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditBasicBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditRoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditEBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditERoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GoBackButtonAddBikesMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(172, 172, 172)))
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(GoBackButtonAddBikesMenu))
                .addGap(50, 50, 50)
                .addComponent(EditBasicBikeButton)
                .addGap(18, 18, 18)
                .addComponent(EditMountainBikeButton)
                .addGap(18, 18, 18)
                .addComponent(EditRoadBikeButton)
                .addGap(18, 18, 18)
                .addComponent(EditEBikeButton)
                .addGap(18, 18, 18)
                .addComponent(EditERoadBikeButton)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditMountainBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMountainBikeButtonMouseClicked
        this.toBack();
        EditMountainBike a =new EditMountainBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_EditMountainBikeButtonMouseClicked

    private void EditRoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditRoadBikeButtonMouseClicked

        this.toFront();
        EditRoadBike a =new EditRoadBike();
        a.setVisible(true);
        a.toFront();

    }//GEN-LAST:event_EditRoadBikeButtonMouseClicked

    private void EditEBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEBikeButtonMouseClicked
        this.toBack();
        EditEBike a = new EditEBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_EditEBikeButtonMouseClicked

    private void EditERoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditERoadBikeButtonMouseClicked
        this.toBack();
        EditERoadBike a = new EditERoadBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_EditERoadBikeButtonMouseClicked

    private void EditERoadBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditERoadBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditERoadBikeButtonActionPerformed

    private void GoBackButtonAddBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuMouseClicked
        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonAddBikesMenuMouseClicked

    private void GoBackButtonAddBikesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonAddBikesMenuActionPerformed

    private void EditBasicBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBasicBikeButtonMouseClicked
        this.toBack();
        EditBasicBike a =new EditBasicBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_EditBasicBikeButtonMouseClicked

    private void EditBasicBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBasicBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBasicBikeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBikesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditBasicBikeButton;
    private javax.swing.JButton EditEBikeButton;
    private javax.swing.JButton EditERoadBikeButton;
    private javax.swing.JButton EditMountainBikeButton;
    private javax.swing.JButton EditRoadBikeButton;
    private javax.swing.JToggleButton GoBackButtonAddBikesMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
