/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;
//////// THIS FILE IS RUN FIRST \\\\\\\\


//***CITATIONS***\\
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//Citations for all occurances similar to lines 170-173 across the program are from https://www.youtube.com/watch?v=Ivarn2HY4Lg&ab_channel=ArtofCoding
//In the file called Add_Basic_Bike.java , all occurances similar to lines 145-148 across the program are from https://www.youtube.com/watch?v=Ivarn2HY4Lg&ab_channel=ArtofCoding













import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;


 
 //@author Christopher
 
public class  MainMenu extends javax.swing.JFrame {
Container main = this.getContentPane();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
        
    public void SetMainContainer(){
         this.setContentPane(main);
        this.invalidate();
        this.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBikesButton_MainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayBikesButton = new javax.swing.JButton();
        DeleteBikesButton = new javax.swing.JButton();
        SearchBikesButton = new javax.swing.JButton();
        EditBikesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBikesButton_MainMenu.setText("Add Bikes");
        addBikesButton_MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBikesButton_MainMenuMouseClicked(evt);
            }
        });
        addBikesButton_MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBikesButton_MainMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Main Menu");

        DisplayBikesButton.setText("Display Bikes");
        DisplayBikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayBikesButtonMouseClicked(evt);
            }
        });
        DisplayBikesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBikesButtonActionPerformed(evt);
            }
        });

        DeleteBikesButton.setText("Delete Bikes");
        DeleteBikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBikesButtonMouseClicked(evt);
            }
        });
        DeleteBikesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBikesButtonActionPerformed(evt);
            }
        });

        SearchBikesButton.setText("Search Bikes");
        SearchBikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBikesButtonMouseClicked(evt);
            }
        });
        SearchBikesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBikesButtonActionPerformed(evt);
            }
        });

        EditBikesButton.setText("Edit Bikes");
        EditBikesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBikesButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBikesButton_MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(DisplayBikesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteBikesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchBikesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditBikesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(addBikesButton_MainMenu)
                .addGap(18, 18, 18)
                .addComponent(DisplayBikesButton)
                .addGap(18, 18, 18)
                .addComponent(DeleteBikesButton)
                .addGap(18, 18, 18)
                .addComponent(SearchBikesButton)
                .addGap(18, 18, 18)
                .addComponent(EditBikesButton)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //this is what happens when the user presses the add bikes button:
    private void addBikesButton_MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBikesButton_MainMenuMouseClicked
    this.toBack();
    Add_Bike_Menu myAddBikesButton_MainMenu = new Add_Bike_Menu();
    myAddBikesButton_MainMenu.setVisible(true);
    myAddBikesButton_MainMenu.toFront();
    }//GEN-LAST:event_addBikesButton_MainMenuMouseClicked

    private void addBikesButton_MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBikesButton_MainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBikesButton_MainMenuActionPerformed

    private void DisplayBikesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBikesButtonActionPerformed

    }//GEN-LAST:event_DisplayBikesButtonActionPerformed

    private void DisplayBikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayBikesButtonMouseClicked

    this.toBack();
    DisplayBikesMenu myDisplayBikesMenu = new DisplayBikesMenu();
    myDisplayBikesMenu.setVisible(true);
    myDisplayBikesMenu.toFront();





    }//GEN-LAST:event_DisplayBikesButtonMouseClicked

    private void DeleteBikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBikesButtonMouseClicked

    this.toBack();
    DeleteBikesMenu myDeleteBikesMenu = new DeleteBikesMenu();
    myDeleteBikesMenu.setVisible(true);
    myDeleteBikesMenu.toFront();



        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBikesButtonMouseClicked

    private void DeleteBikesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBikesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBikesButtonActionPerformed

    private void SearchBikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBikesButtonMouseClicked
    this.toBack();
    SearchBikesMenu mySearchBikesMenu = new SearchBikesMenu();
    mySearchBikesMenu.setVisible(true);
    mySearchBikesMenu.toFront();



        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBikesButtonMouseClicked

    private void SearchBikesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBikesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBikesButtonActionPerformed

    private void EditBikesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBikesButtonMouseClicked

        this.toBack();
        EditBikesMenu a = new EditBikesMenu();
        a.setVisible(true);
        a.toFront();


        // TODO add your handling code here:
    }//GEN-LAST:event_EditBikesButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        InventoryControlGUI.InitInventories();
        InventoryControlGUI.PopulateInventories();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBikesButton;
    private javax.swing.JButton DisplayBikesButton;
    private javax.swing.JButton EditBikesButton;
    private javax.swing.JButton SearchBikesButton;
    private javax.swing.JButton addBikesButton_MainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
