/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class SearchMountainBike extends javax.swing.JFrame {

    /**
     * Creates new form SearchMountainBike
     */
    public SearchMountainBike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxMB = new javax.swing.JComboBox<>();
        input_box_forAllCasesMB = new javax.swing.JTextField();
        submitButtonSearchMB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCase1_SearchMB = new javax.swing.JTextArea();
        BackButton_SearchBB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Search Mountain Bike Menu");

        jComboBoxMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speed Rating", "Num of Gears", "Color Search", "Keyword search", "Seat Height", "Full Suspension", "Flatproof tires" }));

        submitButtonSearchMB.setText("Submit");
        submitButtonSearchMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonSearchMBMouseClicked(evt);
            }
        });
        submitButtonSearchMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonSearchMBActionPerformed(evt);
            }
        });

        textAreaCase1_SearchMB.setColumns(20);
        textAreaCase1_SearchMB.setRows(5);
        jScrollPane2.setViewportView(textAreaCase1_SearchMB);

        BackButton_SearchBB.setText("Go Back");
        BackButton_SearchBB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton_SearchBBMouseClicked(evt);
            }
        });
        BackButton_SearchBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_SearchBBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton_SearchBB)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(input_box_forAllCasesMB, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitButtonSearchMB)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BackButton_SearchBB))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_box_forAllCasesMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButtonSearchMB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonSearchMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonSearchMBMouseClicked
        InventoryControlGUI.type= this.jComboBoxMB.getSelectedIndex()+1;

        if (InventoryControlGUI.type == 1)
        {
            InventoryControlGUI.target_Speed = Integer.parseInt(input_box_forAllCasesMB.getText());
            System.out.println("hey");

        }
        if(InventoryControlGUI.type == 2)
        {
            InventoryControlGUI.target_Gears = Integer.parseInt(input_box_forAllCasesMB.getText());

        }
        if(InventoryControlGUI.type == 3)
        {
            InventoryControlGUI.target_Color = input_box_forAllCasesMB.getText();

        }
        if(InventoryControlGUI.type == 4)
        {
            InventoryControlGUI.target_Keyword = input_box_forAllCasesMB.getText();

        }
        if(InventoryControlGUI.type == 5)
        {
            InventoryControlGUI.target_seatHeight = Integer.parseInt(input_box_forAllCasesMB.getText());

        }
        
        InventoryControlGUI.searchMountainBikeInventory(InventoryControlGUI.myMountainBikeInventory, true,100,InventoryControlGUI.type);

    }//GEN-LAST:event_submitButtonSearchMBMouseClicked

    private void submitButtonSearchMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonSearchMBActionPerformed

    }//GEN-LAST:event_submitButtonSearchMBActionPerformed

    private void BackButton_SearchBBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_SearchBBMouseClicked
        this.toBack();
        setVisible(false);
        new SearchBikesMenu().toFront();
        new SearchBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_BackButton_SearchBBMouseClicked

    private void BackButton_SearchBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_SearchBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButton_SearchBBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMountainBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMountainBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_SearchBB;
    private javax.swing.JTextField input_box_forAllCasesMB;
    private javax.swing.JComboBox<String> jComboBoxMB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitButtonSearchMB;
    public static javax.swing.JTextArea textAreaCase1_SearchMB;
    // End of variables declaration//GEN-END:variables
}
