/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 * input_box_forAllCases
 */
public class SearchEBike extends javax.swing.JFrame {
    public static String x;

    /**
     * Creates new form SearchBasicBike
     */
    public SearchEBike() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        submitButtonSearchBB = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        input_box_forAllCases = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCase1_SearchBB1 = new javax.swing.JTextArea();
        BackButton_SearchBB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Search E Bike Menu");

        submitButtonSearchBB.setText("Submit");
        submitButtonSearchBB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonSearchBBMouseClicked(evt);
            }
        });
        submitButtonSearchBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonSearchBBActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speed Rating", "Num of Gears", "Color Search", "Keyword search", "Range miles", "Battery type", "Battery size", "Battery volt", "Motor power", " " }));

        textAreaCase1_SearchBB1.setColumns(20);
        textAreaCase1_SearchBB1.setRows(5);
        jScrollPane2.setViewportView(textAreaCase1_SearchBB1);

        BackButton_SearchBB.setText("Go Back");
        BackButton_SearchBB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton_SearchBBMouseClicked(evt);
            }
        });
        BackButton_SearchBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_SearchBBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton_SearchBB)
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input_box_forAllCases, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButtonSearchBB)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BackButton_SearchBB))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_box_forAllCases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButtonSearchBB))
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonSearchBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonSearchBBActionPerformed
        
    }//GEN-LAST:event_submitButtonSearchBBActionPerformed

    private void submitButtonSearchBBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonSearchBBMouseClicked
        InventoryControlGUI.type= this.jComboBox1.getSelectedIndex()+1;
         //String x = input_box_forAllCases.getText();
         
        if (InventoryControlGUI.type == 1)
        {
            InventoryControlGUI.target_Speed = Integer.parseInt(input_box_forAllCases.getText());
            System.out.println(InventoryControlGUI.target_Speed);

            
        }
        if(InventoryControlGUI.type == 2)
        {
            InventoryControlGUI.target_Gears = Integer.parseInt(input_box_forAllCases.getText());

        }
        if(InventoryControlGUI.type == 3)
        {
            InventoryControlGUI.target_Color = input_box_forAllCases.getText();

        }
        if(InventoryControlGUI.type == 4)
        {
            InventoryControlGUI.target_Keyword = input_box_forAllCases.getText();

        }
        
        if(InventoryControlGUI.type == 5)
        {
            InventoryControlGUI.target_rangeMiles = Integer.parseInt(input_box_forAllCases.getText());

        }
        
        if(InventoryControlGUI.type == 6)
        {
            InventoryControlGUI.target_batteryType = input_box_forAllCases.getText();

        }
        if(InventoryControlGUI.type == 7)
        {
            InventoryControlGUI.target_batterySize = Integer.parseInt(input_box_forAllCases.getText());

        }
        if(InventoryControlGUI.type == 8)
        {
            InventoryControlGUI.target_batteryVolt = Integer.parseInt(input_box_forAllCases.getText());

        }
        if(InventoryControlGUI.type == 9)
        {
            InventoryControlGUI.target_motorPower = Double.parseDouble(input_box_forAllCases.getText());

        }
        String pr=InventoryControlGUI.searchEBikeInventory(InventoryControlGUI.myEBikeInventory, true,100,InventoryControlGUI.type);
        this.textAreaCase1_SearchBB1.setText(pr);
        
        


    }//GEN-LAST:event_submitButtonSearchBBMouseClicked

    private void BackButton_SearchBBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton_SearchBBMouseClicked
        this.toBack();
        setVisible(false);
        new SearchBikesMenu().toFront();
        new SearchBikesMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_BackButton_SearchBBMouseClicked

    private void BackButton_SearchBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_SearchBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButton_SearchBBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEBike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEBike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_SearchBB;
    private javax.swing.JTextField input_box_forAllCases;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitButtonSearchBB;
    public static javax.swing.JTextArea textAreaCase1_SearchBB1;
    // End of variables declaration//GEN-END:variables
}
