/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.comsc_1451_project;

/**
 *
 * @author Christopher
 */
public class SearchBikesMenu extends javax.swing.JFrame {

    /**
     * Creates new form SearchBikesMenu
     */
    public SearchBikesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GoBackButtonAddBikesMenu = new javax.swing.JToggleButton();
        SearchBasicBikeButton = new javax.swing.JButton();
        SearchMountainBikeButton = new javax.swing.JButton();
        SearchRoadBikeButton = new javax.swing.JButton();
        SearchEBikeButton = new javax.swing.JButton();
        SearchERoadBikeButton = new javax.swing.JButton();

        jLabel3.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Search Bikes Menu");

        GoBackButtonAddBikesMenu.setText("Go Back");
        GoBackButtonAddBikesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonAddBikesMenuMouseClicked(evt);
            }
        });
        GoBackButtonAddBikesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonAddBikesMenuActionPerformed(evt);
            }
        });

        SearchBasicBikeButton.setText("Search Basic Bike");
        SearchBasicBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBasicBikeButtonMouseClicked(evt);
            }
        });
        SearchBasicBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBasicBikeButtonActionPerformed(evt);
            }
        });

        SearchMountainBikeButton.setText("Search Mountain Bike");
        SearchMountainBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMountainBikeButtonMouseClicked(evt);
            }
        });
        SearchMountainBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMountainBikeButtonActionPerformed(evt);
            }
        });

        SearchRoadBikeButton.setText("Search Road Bike");
        SearchRoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchRoadBikeButtonMouseClicked(evt);
            }
        });
        SearchRoadBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRoadBikeButtonActionPerformed(evt);
            }
        });

        SearchEBikeButton.setText("Search Electric Bike");
        SearchEBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchEBikeButtonMouseClicked(evt);
            }
        });

        SearchERoadBikeButton.setText("Search Electric Road Bike");
        SearchERoadBikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchERoadBikeButtonMouseClicked(evt);
            }
        });
        SearchERoadBikeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchERoadBikeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GoBackButtonAddBikesMenu)
                        .addGap(205, 205, 205)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchMountainBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBasicBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchRoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchEBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchERoadBikeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(GoBackButtonAddBikesMenu))
                .addGap(25, 25, 25)
                .addComponent(SearchBasicBikeButton)
                .addGap(18, 18, 18)
                .addComponent(SearchMountainBikeButton)
                .addGap(18, 18, 18)
                .addComponent(SearchRoadBikeButton)
                .addGap(18, 18, 18)
                .addComponent(SearchEBikeButton)
                .addGap(18, 18, 18)
                .addComponent(SearchERoadBikeButton)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonAddBikesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuMouseClicked
        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_GoBackButtonAddBikesMenuMouseClicked

    private void GoBackButtonAddBikesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonAddBikesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackButtonAddBikesMenuActionPerformed

    private void SearchBasicBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBasicBikeButtonMouseClicked
        this.toBack();
        SearchBasicBike a = new SearchBasicBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_SearchBasicBikeButtonMouseClicked

    private void SearchBasicBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBasicBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBasicBikeButtonActionPerformed

    private void SearchMountainBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMountainBikeButtonMouseClicked
        this.toBack();
      SearchMountainBike a =new SearchMountainBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_SearchMountainBikeButtonMouseClicked

    private void SearchRoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchRoadBikeButtonMouseClicked

        this.toFront();
      SearchRoadBike a =new SearchRoadBike();
        a.setVisible(true);
        a.toFront();

    }//GEN-LAST:event_SearchRoadBikeButtonMouseClicked

    private void SearchEBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEBikeButtonMouseClicked
        this.toBack();
       SearchEBike a = new SearchEBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_SearchEBikeButtonMouseClicked

    private void SearchERoadBikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchERoadBikeButtonMouseClicked
        this.toBack();
        SearchERoadBike a = new SearchERoadBike();
        a.setVisible(true);
        a.toFront();
    }//GEN-LAST:event_SearchERoadBikeButtonMouseClicked

    private void SearchERoadBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchERoadBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchERoadBikeButtonActionPerformed

    private void SearchMountainBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMountainBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMountainBikeButtonActionPerformed

    private void SearchRoadBikeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRoadBikeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchRoadBikeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBikesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBikesMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton GoBackButtonAddBikesMenu;
    private javax.swing.JButton SearchBasicBikeButton;
    private javax.swing.JButton SearchEBikeButton;
    private javax.swing.JButton SearchERoadBikeButton;
    private javax.swing.JButton SearchMountainBikeButton;
    private javax.swing.JButton SearchRoadBikeButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
