/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.AcademicAdviser;

/**
 *
 * @author 124ch
 */
public class EditExistingProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditExistingProfile
     */
    public EditExistingProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ChangeGeneralStudentProfileInfoButton = new javax.swing.JButton();
        AddCoursesMajorMinorToStudentProfileButton = new javax.swing.JButton();
        EditExistingProfileScreenBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit existing profile screen");

        ChangeGeneralStudentProfileInfoButton.setText("Change general student profile information");
        ChangeGeneralStudentProfileInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeGeneralStudentProfileInfoButtonMouseClicked(evt);
            }
        });

        AddCoursesMajorMinorToStudentProfileButton.setText("Add courses, major, minor to student profile");
        AddCoursesMajorMinorToStudentProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCoursesMajorMinorToStudentProfileButtonMouseClicked(evt);
            }
        });
        AddCoursesMajorMinorToStudentProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCoursesMajorMinorToStudentProfileButtonActionPerformed(evt);
            }
        });

        EditExistingProfileScreenBackButton.setText("Go back");
        EditExistingProfileScreenBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditExistingProfileScreenBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddCoursesMajorMinorToStudentProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeGeneralStudentProfileInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(EditExistingProfileScreenBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(EditExistingProfileScreenBackButton))
                .addGap(39, 39, 39)
                .addComponent(ChangeGeneralStudentProfileInfoButton)
                .addGap(28, 28, 28)
                .addComponent(AddCoursesMajorMinorToStudentProfileButton)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditExistingProfileScreenBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditExistingProfileScreenBackButtonMouseClicked
        // TODO add your handling code here:
        
        MainMenu mainScreen = new MainMenu();
        mainScreen.toFront();
        mainScreen.setState(java.awt.Frame.NORMAL);
        mainScreen.setVisible(true);
        
        this.toBack();
        setVisible(false);
        
        
    }//GEN-LAST:event_EditExistingProfileScreenBackButtonMouseClicked

    private void ChangeGeneralStudentProfileInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeGeneralStudentProfileInfoButtonMouseClicked
        // TODO add your handling code here:
        
        
        ChangeGeneralStudentProfileInfo screen3 = new ChangeGeneralStudentProfileInfo();
        screen3.toFront();
        screen3.setState(java.awt.Frame.NORMAL);
        screen3.setVisible(true);
        
        this.toBack();
        setVisible(false);
    }//GEN-LAST:event_ChangeGeneralStudentProfileInfoButtonMouseClicked

    private void AddCoursesMajorMinorToStudentProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCoursesMajorMinorToStudentProfileButtonMouseClicked
        // TODO add your handling code here:
        
        AddCourseMajorMinor screen6 = new AddCourseMajorMinor();
        screen6.toFront();
        screen6.setState(java.awt.Frame.NORMAL);
        screen6.setVisible(true);
        
        this.toBack();
        this.setVisible(false);
        
        
    }//GEN-LAST:event_AddCoursesMajorMinorToStudentProfileButtonMouseClicked

    private void AddCoursesMajorMinorToStudentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCoursesMajorMinorToStudentProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCoursesMajorMinorToStudentProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditExistingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditExistingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditExistingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditExistingProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditExistingProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCoursesMajorMinorToStudentProfileButton;
    private javax.swing.JButton ChangeGeneralStudentProfileInfoButton;
    private javax.swing.JButton EditExistingProfileScreenBackButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
