/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.AcademicAdviser;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Hashtable;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author 124ch
 */
public class MainMenu extends javax.swing.JFrame {
    static Hashtable<Integer, Student> StudentIndex = new Hashtable<>();

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateStudentProfileButton = new javax.swing.JButton();
        EditStudentProfileButton = new javax.swing.JButton();
        ViewStudentProfileButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COMSC 2351 with Dr. Charles Thangaraj");

        jLabel2.setText("Academic Adviser project by Christopher Ian Lama");

        jLabel3.setText("Main Menu");

        CreateStudentProfileButton.setText("Create Student Profile");
        CreateStudentProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateStudentProfileButtonMouseClicked(evt);
            }
        });
        CreateStudentProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateStudentProfileButtonActionPerformed(evt);
            }
        });

        EditStudentProfileButton.setText("Edit Student Profile");
        EditStudentProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditStudentProfileButtonMouseClicked(evt);
            }
        });
        EditStudentProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStudentProfileButtonActionPerformed(evt);
            }
        });

        ViewStudentProfileButton.setText("View Student Profile");
        ViewStudentProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewStudentProfileButtonMouseClicked(evt);
            }
        });

        jButton1.setText("Load Student Profiles");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(447, 447, 447))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(315, 315, 315))))
            .addGroup(layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EditStudentProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateStudentProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewStudentProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(CreateStudentProfileButton)
                .addGap(18, 18, 18)
                .addComponent(EditStudentProfileButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewStudentProfileButton)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateStudentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateStudentProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateStudentProfileButtonActionPerformed

    private void CreateStudentProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateStudentProfileButtonMouseClicked
        // TODO add your handling code here:
        CreateStudentProfile screen1 = new CreateStudentProfile();
        screen1.toFront();
        screen1.setState(java.awt.Frame.NORMAL);
        screen1.setVisible(true);
        
        this.toBack();
        this.setVisible(false);
       
        
        
    }//GEN-LAST:event_CreateStudentProfileButtonMouseClicked

    private void EditStudentProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditStudentProfileButtonMouseClicked
        // TODO add your handling code here:
        
        EditExistingProfile screen2 = new EditExistingProfile();
        screen2.toFront();
        screen2.setState(java.awt.Frame.NORMAL);
        screen2.setVisible(true);
        
        this.toBack();
        this.setVisible(false);
        
    }//GEN-LAST:event_EditStudentProfileButtonMouseClicked

    private void ViewStudentProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStudentProfileButtonMouseClicked
        // TODO add your handling code here:
        
        
        ViewStudentProfile screen7 = new ViewStudentProfile();
        screen7.toFront();
        screen7.setState(java.awt.Frame.NORMAL);
        screen7.setVisible(true);
        
        this.toBack();
        this.setVisible(false); 
        
    }//GEN-LAST:event_ViewStudentProfileButtonMouseClicked

    private void EditStudentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditStudentProfileButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
//        Scanner read = new Scanner( new File("src\\main\\java\\project\\AcademicAdviser\\CSV_FILE.txt"));
        
        BufferedReader readFile = new BufferedReader(new FileReader("CSV_FILE.txt")); // "src\\main\\java\\project\\AcademicAdviser\\CSV_FILE.txt"
        
        String newLine = readFile.readLine();
        while(newLine != null){ 
            Student.PopulateFromCSV(MainMenu.StudentIndex, newLine.split(","));
            
            newLine = readFile.readLine();
        }
        
        readFile.close();
        
        JOptionPane.showMessageDialog(null, "Loaded student profiles to index");
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, " ERROR: Could not load student profiles to index");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateStudentProfileButton;
    private javax.swing.JButton EditStudentProfileButton;
    private javax.swing.JButton ViewStudentProfileButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
